server:
  # 服务端口
  port: 9999

spring:
  # mysql数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/a33
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 192.168.163.128
  banner:
    image:
      location: bug.png
      
logging:
  level:
    com.a33: debug
